2021-01-08 19:38:32.063 - INFO - 8096 - azureml.train.automl.automlconfig._start_execution:207 - Submitting remote.
2021-01-08 19:53:40.167 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-01-08 19:53:40.243 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-01-08 19:53:40.330 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-01-08 19:53:40.613 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-01-08 19:53:41.286 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:53:41.288 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=674.3[ms]
2021-01-08 19:53:41.295 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:53:41.298 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=966.35[ms]
2021-01-08 19:53:41.304 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:53:41.306 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1062.35[ms]
2021-01-08 19:53:41.313 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 688, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:53:41.315 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=1148.32[ms]
2021-01-08 19:59:18.464 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-01-08 19:59:18.534 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-01-08 19:59:18.587 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-01-08 19:59:18.796 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-01-08 19:59:19.390 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:19.392 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=595.84[ms]
2021-01-08 19:59:19.398 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:19.400 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=813.02[ms]
2021-01-08 19:59:19.405 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:19.407 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=873.03[ms]
2021-01-08 19:59:19.413 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 688, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:19.415 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=951.03[ms]
2021-01-08 19:59:40.304 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-01-08 19:59:40.389 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetOutput
2021-01-08 19:59:40.451 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-01-08 19:59:40.640 - INFO - 8096 - azureml.train.automl.run._log_activity:54 - ActivityStarted: GetChildren
2021-01-08 19:59:41.161 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:41.161 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=521.69[ms]
2021-01-08 19:59:41.166 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:41.167 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=716.03[ms]
2021-01-08 19:59:41.169 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:41.175 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=785.13[ms]
2021-01-08 19:59:41.182 - CRITICAL - 8096 - azureml.train.automl.run.log_traceback:224 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 57, in _log_activity
    yield
  File "run.py", line 688, in get_output
    activity_name=automl_shared_constants.TelemetryConstants.GET_OUTPUT
  File "run.py", line 618, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 776, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(metric)
  File "run.py", line 817, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2021-01-08 19:59:41.182 - INFO - 8096 - azureml.train.automl.run._log_activity:92 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=877.15[ms]
2021-01-08 20:07:10.524 - INFO - 8096 - azureml.train.automl.automlconfig._start_execution:207 - Submitting remote.
2021-01-08 20:22:32.232 - INFO - 8096 - azureml.train.automl.automlconfig._start_execution:207 - Submitting remote.
